name: goodaction
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.1
  provider: ^6.1.2
  go_router: ^14.2.2
  get: ^4.6.6
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/svgiocon/

  fonts:
    - family: inter
      fonts:
        - asset: assets/icons/font/inter/Inter_18pt-SemiBold.ttf
          weight: 900
        - asset: assets/icons/font/inter/Inter_18pt-SemiBold.ttf
          weight: 800
        - asset: assets/icons/font/inter/Inter_18pt-Regular.ttf
          weight: 700
        - asset: assets/icons/font/inter/Inter_18pt-Regular.ttf
          weight: 600
        - asset: assets/icons/font/inter/Inter_18pt-Black.ttf
          weight: 500
        - asset: assets/icons/font/inter/Inter_18pt-Medium.ttf
          weight: 400

